services:
    php:
        container_name: api-php
        build:
            context: ./
            dockerfile: "./docker/php/Dockerfile"
            args:
                user: sammy
                uid: 1000
        environment:
            XDEBUG_CONFIG: "remote_host={{127.0.0.1}}"
            PHP_IDE_CONFIG: "serverName=host.docker.internal"
        working_dir: /var/www/html
        ports:
            - "5174:5173"
        networks:
            - api_network
        volumes:
            - ./:/var/www/html:cached
            - ./node_modules:/var/www/html/node_modules:delegated
            - ./public:/var/www/html/public:delegated

    nginx:
        container_name: api-nginx
        image: nginx
        environment:
            NGINX_STATIC_OPEN_FILE_CACHE: "off"
            NGINX_ERROR_LOG_LEVEL: debug
            NGINX_BACKEND_HOST: php
            NGINX_VHOST_PRESET: php
            NGINX_SERVER_ROOT: /var/www/html/public
        ports:
            -   '88:80'
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d/
            - ./public:/var/www/html/public:delegated
            - ./storage/app/public:/var/www/html/storage/app/public:delegated
        networks:
            - api_network

    mysql:
        image: mysql
        container_name: api-mysql
        volumes:
            - ./docker/mysql:/var/lib/mysql:rw
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: db
            MYSQL_PASSWORD: db
        ports:
            -   '34001:3306'
        networks:
            - api_network

networks:
    api_network:
        external: false
